[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Configure secrets scanning to ignore Next.js public env vars
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CONVEX_URL"

# Next.js runtime configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase timeout for PDF generation
  "*" = { timeout = 30 }