[build]
  command = "npx convex deploy --cmd 'npm run build:netlify'"
  publish = ".next"

[build.environment]
  # Configure secrets scanning to ignore Next.js public env vars and LLM model names
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CONVEX_URL,LLM_MODEL_CHEAP,LLM_MODEL_BURST,LLM_PROVIDER,CONVEX_DEPLOYMENT"
  NODE_VERSION = "18"
  CHROMIUM_CHANNEL = "stable"

# Next.js runtime configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium","puppeteer-core"]
  included_files = [
    "public/**"               # ensure CSS/fonts/logo are bundled for the function
  ]
  timeout = 26               # max allowed on Netlify
  memory = 1536              # give Chromium room